package com.wlk.android.job_club.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.wlk.android.job_club.database.TestData;

import com.wlk.android.job_club.database.TestDataDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig testDataDaoConfig;

    private final TestDataDao testDataDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        testDataDaoConfig = daoConfigMap.get(TestDataDao.class).clone();
        testDataDaoConfig.initIdentityScope(type);

        testDataDao = new TestDataDao(testDataDaoConfig, this);

        registerDao(TestData.class, testDataDao);
    }
    
    public void clear() {
        testDataDaoConfig.clearIdentityScope();
    }

    public TestDataDao getTestDataDao() {
        return testDataDao;
    }

}
